config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    get 'about', to: 'pages#about'
    resources :articles
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :categories

end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 7000 }
    def self.search_by(search_term)
        where("LOWER(title) LIKE :search_term OR LOWER(description) LIKE :search_term ",
         search_term: "%#{search_term.downcase}%")
    end
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def show
        
        
    end
    def index
        
        @articles = Article.paginate(page: params[:page], per_page: 5)
        if params[:search]
            @search_term = params[:search]
            @articles = @articles.search_by(@search_term)
            
        end
        if params[:order]
            @ordered = params[:order].to_i
        
            if @ordered  === 1
             @articles = @articles.order(created_at: :desc)
            else 
                @articles = @articles.order(created_at: :ASC)
            end

        end
      
    end
    def new
        @article = Article.new
    end
    def edit
        
    end
    def create 
        @article = Article.new(article_params)
     
        @article.user = current_user

        if @article.save
            redirect_to article_path(@article), success: "Article was created successfully."
        else
            render 'new'
        end
    end

    def update
        if @article.update(article_params)
            redirect_to article_path(@article), success: "Article was updated successfully."
        else
            render 'edit'
        end
    end
    def destroy
        @article.destroy
        redirect_to articles_path

    end
    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            redirect_to @article, danger: "You can only update and/or delete your own articles"
        end
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
    <div class="container">

    <%= form_with(model: @article, local: true, class: "shadow-lg p-3 mb-3 bg-info rounded text-center", method: "get") do %>
        <%= label_tag(:search, "Search for:") %>
        <%= text_field_tag :search, @search_term,placeholder: "Article" %>
        <%= label_tag(:order, "Sort by:", class: "ml-5") %>
        <%= select_tag(:order, options_for_select([['Newest first', 1], ['Oldest first', 2]], params[:order]),{:include_blank => true}) %>
        <%= submit_tag("Search") %> 
    <% end %>



    <% @articles.each do |article|%>
        <div class="row justify-content-center">
        <div class="col-md-8 mt-4">
            <div class="card text-center shadow-lg mb-5 bg-white rounded">
            <div class="card-header font-italic">
            <% if article.user %>
                by <%= link_to article.user.username, user_path(article.user) %><br>
            <% end %>
            <% if article.categories.any? %>
                <div class="mt-2"> <%= render article.categories %></div>
            <% else %>
                <div class="mt-2 badge badge-pill badge-secondery">not Categorized</div>
            <% end %>
            </div>
            <div class="card-body">
                <h5 class="card-title"> <%= link_to article.title, article_path(article), class: "text-success" %></h5>
                <p class="card-text"><%= truncate(article.description, length: 50) %></p>
                <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
                <% if logged_in? && (article.user === current_user || current_user.admin?)%>
                    <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
                    <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>            
                <% end %>
            </div>
            <div class="card-footer text-muted">
                <small> Created <%= time_ago_in_words(article.created_at) %> ago , 
                edited <%= time_ago_in_words(article.updated_at) %> ago</small>
            </div>
            </div>
        </div>
        </div>
        
    <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">

<div class="row justify-content-center mb-4">
<div  class="col-10">
<%= render "shared/errors", obj: @article %>
<%= form_with(model: @article, local: true, class: "shadow-lg p-3 mb-3 bg-info rounded") do |f| %>
    
    <div class="form-group row ">
        <%= f.label :title, class: "col-2 col-form-label text-light" %><br>
        <div class="col-10">
            <%= f.text_field :title, placeholder: "Article tiltle", class: "form-control shadow-lg rounded" %>
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :description, class: "col-2 col-form-label text-light" %><br>
        <div class="col-10">
            <%= f.text_area :description, rows: 10, placeholder: "Article text", class: "form-control shadow-lg rounded" %>
        </div>
    </div>     
    <div class="form-group row ">
    <%= label_tag(:category, "Categories:", class: "col-2 col-form-label text-light") %><br>
    <div class="col-10"> 
    <%= f.collection_select(:category_ids, Category.all, :id, :name,
                    { prompt: "Make selection"}, {multiple:  true, class: "custom-select mul-select form-control shadow-lg rounded"}) %>            
                       
    </div>
    </div>
    <div class="form-group row d-flex justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>
    </div>

<% end %>
</div>
</div>

   
<center><p> <%= link_to "[ Return to Articles' list without saving ]", articles_path, class: "text-info" %> </p></center>

</div>
<script>
$(document).ready(function(){
    $(".mul-select").select2({
            placeholder: "select categories(optional)", //placeholder
            tags: true,
            tokenSeparators: ['/',',',';'," "] 
        });
    })
</script>

app/views/articles/edit.html.erb
<center><h1 class="mt-4 mb-4">Edit article</h1></center>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="workspace">

<div class="mt-10">

  <center><h1 class="mt-4">Articles List</h1></center>
  <% if logged_in? %>
  <div class="wrap">
    <button id="add-btn" class="button"><%= link_to "Add New", new_article_path, class: "noDecoration" %></button>
  </div>
<% end %>
</div>
  <div class="flickr_pagination mb-4">
    
    <%= will_paginate @articles, :container => false %>
  </div>
    <%= render "articles/articles" %>
    <div class="flickr_pagination mb-4">
    
    <%= will_paginate @articles, :container => false %>
  </div>

</div>

app/views/articles/new.html.erb
<center><h1 class="mt-4 mb-4">Create a new article</h1></center>
    
<%= render 'form' %>

app/views/articles/show.html.erb
   <h2 class="text-center mt-4"><%= @article.title %></h2>
   <div class="container">
        <div class="row justify-content-md-center ml-10">
            <div class="col-md-8 col-sm-12 mt-4">
                <div class="card text-center shadow-lg mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                        by <%= @article.user.username %>
                        <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
                        <% if @article.categories.any? %>
                           <div class="mt-2"> <%= render @article.categories %></div>
                        <% else %>
                        <div class="mt-2 badge badge-pill badge-secondery">not Categorized</div>
                        <% end %>
                    </div>
                    <div class="card-body">
                    <div class="card-text text-justify"><%=simple_format(@article.description) %></div>
                    <% if logged_in? && (@article.user === current_user || current_user.admin?)%>
                        <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
                        <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>            
                    <% end %>
                    </div>
                    <div class="card-footer text-muted">
                    <small> Created <%= time_ago_in_words(@article.created_at) %> ago , 
                    edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
    </div>