config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    get 'about', to: 'pages#about'
    resources :articles
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :categories

end

app/views/pages/_heading.html.erb
  <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Alpha Blog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Articles
        </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
            <%= link_to "Articles' List", articles_path, class: "dropdown-item"%>

            <% if logged_in? %>
              <%= link_to "Create new article", new_article_path, class: "dropdown-item"%>
            <% end %>
          </div>
        </li>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categories
        </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
            <%= link_to "Categories' List", categories_path, class: "dropdown-item"%>

            <% if logged_in? && current_user.admin? %>
              <%= link_to "Create new category", new_category_path, class: "dropdown-item"%>
            <% end %>
          </div>
        </li>

        <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link"%>
        </li>
      </ul>


        <div class="navbar-nav">
        <% if logged_in? %>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
        <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Delete your profile", user_path(current_user), method: :delete, data: {confirm: "Are you sure?"}, class: "dropdown-item text-danger" %>
          </div>
      </li>
        <%= link_to "Log out", logout_path, class: "nav-link", method: :delete %>
        <% else %>
        <%= link_to "Log in", login_path, class: "nav-link"%>
        <%= link_to "Sign up", signup_path, class: "nav-link"%>

        <% end %>

        </div>
     
    </div>
  </nav>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<p> <%= link_to "Articles", articles_path %> </p>

app/views/pages/home.html.erb
    <div class="container">
        <div id="home-jumbo" class="jumbotron text-center d-flex align-items-center">
            <div>    
                <div>
                    <h1 class="display-4 mt-100">Alpha Blog</h1>
                </div>
                <div>
                    <p class="lead">This is a blog</p>
                    <hr class="my-4">
                    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
                    <%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg"%>

                </div>
            </div>
        </div>
    </div>